stages:
  - .pre
  - preparation
  - secret_detection
  - sbom_scan
  - test
  - build
  - build_test
  - push_image
  - sign_image
  - update_k8s_manifest

variables:
  DD_NOT_ON_MASTER: "false"

.composer:
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  stage: preparation
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month    
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

.npm:
  image: node:20-alpine
  stage: preparation
  needs:
    - composer
  cache:
    key: $CI_PROJECT_NAME-npm
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    expire_in: 30 days
    paths:
      - node_modules/
      - public/build/


.secret_detection:
  stage: secret_detection
  #dependencies: ["defectdojo_create_engagement"]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 1
    DD_SCAN_TYPE: "Gitleaks Scan"
    DD_PRODUCT_NAME: "GitLeaks"
    DD_SCAN_FILE: "gitleaks-report.json"
    DD_SCAN_ACTIVE: "true"
    DD_SCAN_VERIFIED: "false"
  image: 
    name: harbor.opensecdevops.com/osdo/gitleak@sha256:d348f3c616c5b51b8e6bb1702484d6f293712be43fc81c3b97793f0886b7f95b
    entrypoint: [""]
  script:
    - gitleaks detect -v --source=$PWD  --report-path=gitleaks-report.json
  #after_script:
  #  - |
  #    if [ $CI_JOB_STATUS == 'failed' ]; then
  #      bash .gitlab-ci/defectdojo-finding.sh
  #    fi
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - gitleaks-report.json

.sbom_scan_php:
  stage: sbom_scan
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  dependencies: ['composer']
  variables:
    COMPOSER_ALLOW_SUPERUSER: 1
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer CycloneDX:make-sbom --output-file=sbom.json --output-format=json
    #- sh ../.gitlab-ci/dependency-track.sh 
  allow_failure: true
  artifacts:
    expire_in: 1 days
    paths:
      - sbom.json

.sbom_scan_node:
  stage: sbom_scan
  image: node:20-alpine
  dependencies: ['npm']
  before_script:
    - npm install -g @cyclonedx/cyclonedx-npm@1.14.2
  script:
    - cyclonedx-npm --output-file bom.json --omit dev --short-PURLs
    #- sh ../.gitlab-ci/dependency-track.sh 
  after_script:
    # Add artificial metrics report to collect release evidence
    - echo 'node_sbom run' > metrics.txt
  allow_failure: true
  artifacts:
    paths:
      - bom.json
    reports:
      # Add artificial metrics report to collect release evidence
      metrics: metrics.txt
      cyclonedx: bom.json


.phpunit:
  stage: test
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  dependencies: ['composer', 'npm']
  variables:
    XDEBUG_MODE: coverage
  before_script:
    - php artisan key:generate --env=testing
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never --log-junit phpunit-report.xml --coverage-clover coverage-report.xml
  artifacts:
    paths:
      - phpunit-report.xml
      - coverage-report.xml
    reports:
      junit: phpunit-report.xml
    expire_in: 30 min
  allow_failure: true


.sonarqube-check:
  stage: test
  dependencies: ['phpunit']
  needs: ['phpunit']
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - ls
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

.docker_build:
  stage: build
  dependencies: ['composer', 'npm']
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir tar_images
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/deployment/php/Dockerfile"
      --destination "${DOCKER_REGISTRY_URL}/osdo/osdo-app:${CI_COMMIT_TAG}" --no-push --tar-path tar_images/osdo_app.tar
  artifacts:
    paths:
      - tar_images
    when: on_success

.docker_scan:
  stage: build_test
  dependencies: ["docker_build"]
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  script:
    - mkdir -p scan_result
    - cd tar_images
    - |
      for tar_image in *.tar; 
      do
        [ -e "$tar_image" ] || continue;
        file_name=${tar_image%.*};
        if [ "$vulnerability_scanner" = "trivy" ]; then
          trivy image --timeout 15m --offline-scan --input $tar_image -f json -o ../scan_result/$file_name.json --severity CRITICAL; 
        fi
      done
  # Enables https://docs.gitlab.com/ee/user/application_security/container_scanning/ (Container Scanning report is available on GitLab EE Ultimate or GitLab.com Gold)
  artifacts:
    paths:
      - scan_result
    expire_in: 1 month

.docker_push:
  stage: push_image
  dependencies: ["docker_build"]
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - cd tar_images
    - |
      for tar_image in *.tar; 
      do 
        crane auth login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY_URL;
        crane push $tar_image $DOCKER_REGISTRY_URL/osdo/osdo-app:$CI_COMMIT_SHORT_SHA -v;
        DIGEST=$(crane digest $DOCKER_REGISTRY_URL/osdo/osdo-app:$CI_COMMIT_SHORT_SHA);
        echo "DIGEST=${DIGEST}" >> digest.env
      done
  artifacts:
    reports:
      dotenv: tar_images/digest.env
    expire_in: 10 min

.docker_sign:
  stage: sign_image
  dependencies: ["docker_push"]
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - apk add --update cosign curl bash
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" $DOCKER_REGISTRY_URL
    - cosign sign --key .secure_files/cosign.key -y $DOCKER_REGISTRY_URL/osdo/osdo-app@${DIGEST}

docker_hadolit:
  stage: test
  image:  hadolint/hadolint@sha256:7dba9a9f1a0350f6d021fb2f6f88900998a4fb0aaf8e4330aa8c38544f04db42
  script:
    - hadolint "${CI_PROJECT_DIR}/deployment/php/Dockerfile" -f json > hadolit.json
    - ls
  #after_script:
  #  - |
  #    if [ $CI_JOB_STATUS == 'failed' ]; then
  #      bash .gitlab-ci/defectdojo-finding.sh
  #    fi







