stages:
  - .pre
  - preparation
  - secret_detection
  - sbom_scan
  - test
  - build
  - build_test
  - push_image
  - update_k8s_manifest

variables:
  DD_NOT_ON_MASTER: "false"

composer:
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  stage: preparation
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month    
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

npm:
  image: node:20-alpine
  stage: preparation
  cache:
    key: $CI_PROJECT_NAME-npm
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - ls
  artifacts:
    expire_in: 30 days
    paths:
      - node_modules/


secret_detection:
  stage: secret_detection
  #dependencies: ["defectdojo_create_engagement"]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 1
    DD_SCAN_TYPE: "Gitleaks Scan"
    DD_PRODUCT_NAME: "GitLeaks"
    DD_SCAN_FILE: "gitleaks-report.json"
    DD_SCAN_ACTIVE: "true"
    DD_SCAN_VERIFIED: "false"
  image: 
    name: harbor.opensecdevops.com/osdo/gitleak@sha256:d348f3c616c5b51b8e6bb1702484d6f293712be43fc81c3b97793f0886b7f95b
    entrypoint: [""]
  script:
    - gitleaks detect -v --source=$PWD  --report-path=gitleaks-report.json
  #after_script:
  #  - |
  #    if [ $CI_JOB_STATUS == 'failed' ]; then
  #      bash .gitlab-ci/defectdojo-finding.sh
  #    fi
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - gitleaks-report.json

sbom_scan_php:
  stage: sbom_scan
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  dependencies: ['composer']
  variables:
    COMPOSER_ALLOW_SUPERUSER: 1
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer CycloneDX:make-sbom --output-file=sbom.json --output-format=json
    #- sh ../.gitlab-ci/dependency-track.sh 
  allow_failure: true
  artifacts:
    expire_in: 1 days
    paths:
      - sbom.json

sbom_scan_node:
  stage: sbom_scan
  image: node:20-alpine
  dependencies: ['npm']
  before_script:
    - npm install -g @cyclonedx/cyclonedx-npm@1.14.2
  script:
    - cyclonedx-npm --output-file bom.json --omit dev --short-PURLs
    #- sh ../.gitlab-ci/dependency-track.sh 
  after_script:
    # Add artificial metrics report to collect release evidence
    - echo 'node_sbom run' > metrics.txt
  allow_failure: true
  artifacts:
    paths:
      - bom.json
    reports:
      # Add artificial metrics report to collect release evidence
      metrics: metrics.txt
      cyclonedx: bom.json


phpunit:
  stage: test
  image: harbor.opensecdevops.com/osdo/php-ci@sha256:c4d27b1286fb998148f7439533f83c2ca40f0358bbda6009a6a3f069e14086c0
  dependencies: ['composer', 'npm']
  variables:
    XDEBUG_MODE: coverage
  before_script:
    - php artisan key:generate --env=testing
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never --log-junit phpunit-report.xml
  artifacts:
    paths:
      - phpunit-report.xml
    reports:
      junit: phpunit-report.xml
    expire_in: 30 min
  allow_failure: true
