sonar.projectKey=OSDO-APP
sonar.qualitygate.wait=true
sonar.sources=app
sonar.exclusions=app/Providers/**, vendor/**
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage-report.xml
sonar.php.tests.reportPath=phpunit-report.xml